title: "ASPA"
description: "Official Website"
baseurl: ""
url: "https://theaspa.github.io"
theme: minima

collections:
  blog:
    output: true
    permalink: /blog/:path/

    header_pages:
  - about.md
  - blog.md
  - news.md

