title: "ASPA"
description: "Official Website"
baseurl: ""
url: "https://theaspa.github.io"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

collections:
  blog:
    output: true
    permalink: /blog/:path/

